
import express from 'express';
import { GoogleGenAI } from '@google/genai';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';

dotenv.config();

const app = express();
const port = process.env.PORT || 7860;
const API_KEY = process.env.API_KEY || process.env.GEMINI_API_KEY;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Middleware
app.use((req, res, next) => {
  res.setHeader('Permissions-Policy', 'microphone=(self)');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('X-Frame-Options', 'SAMEORIGIN');
  next();
});

app.use(express.static(path.join(__dirname, 'dist')));
app.use(express.json({ limit: '50mb' }));

if (!API_KEY) {
  console.warn("Warning: API_KEY is missing.");
}

const getAiClient = () => {
    if (!API_KEY) throw new Error("API Key not configured");
    return new GoogleGenAI({ apiKey: API_KEY });
}

const PROMPT_TEXT = `
Task:
Transcribe this recording of my grandpa. Do your best to interpret what he is most likely trying to say, as he has had stroke and has impaired speech.

Output rules:
- Respond ONLY with the estimated transcription.
- Do NOT include explanations, commentary, or extra text.
`;

// --- TRANSCRIPTION ---
app.post('/api/transcribe', async (req, res) => {
  try {
    const ai = getAiClient();
    const { base64Audio, mimeType } = req.body || {};

    if (!base64Audio) return res.status(400).json({ error: "base64Audio required" });

    // Use Gemini 2.0 Flash for fast transcription
    const response = await ai.models.generateContent({
      model: 'gemini-2.0-flash', 
      contents: {
        parts: [
          { inlineData: { mimeType: mimeType, data: base64Audio } },
          { text: PROMPT_TEXT },
        ],
      },
      config: { temperature: 0.4 },
    });

    const text = response.text;
    res.json({ text: text ? text.trim() : "" });
  } catch (error) {
    console.error("Transcription API Error:", error?.message || error);
    res.status(500).json({ error: "Failed to transcribe audio" });
  }
});

// --- GEMINI TTS ---
app.post('/api/tts', async (req, res) => {
  try {
    const ai = getAiClient();
    const { text } = req.body || {};

    if (!text) return res.status(400).json({ error: "text is required" });

    console.log(`Generating Speech for: "${text.substring(0, 20)}..."`);

    // Use Gemini 2.0 Flash Experimental for Audio Generation
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-preview-tts', 
      contents: {
        parts: [{ text: text }],
      },
      config: {
        responseModalities: ['AUDIO'], // Explicitly request Audio
        speechConfig: {
          voiceConfig: {
            // 'Fenrir' is the deep American Male voice in Gemini
            prebuiltVoiceConfig: { voiceName: 'Fenrir' },
          },
        },
      },
    });

    // Extract the raw audio data
    const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    
    if (!base64Audio) throw new Error("No audio generated by Gemini");

    res.json({ audioData: base64Audio });
  } catch (error) {
    console.error("TTS API Error:", error?.message || error);
    res.status(500).json({ error: "Failed to generate speech" });
  }
});

app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});